name = "ieee-ypsl-web"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[vars]
PAYLOAD_SECRET = "ieeeypsl_payload26"
# Add other public variables here if needed
