name = "ieee-ypsl-web"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[vars]
PAYLOAD_SECRET = "ieeeypsl_payload26"
# Add other public variables here if needed
